### ISSUE TITLE
Publish docker image for version v1.5.0

### ISSUE THREAD

**Issue by khernyo** [kiwigrid/k8s-sidecar#103]
Could you please publish a docker image for version v1.5.0?

This is related to the PR #102, which eliminates several security vulnerabilities in the latest (1.3.0) published docker image.

**Comment by monotek** [comment]
All people who would care and could approve a pr or push an image do not work for kiwigrid anymore.
You might want to fork...

**Comment by khernyo** [comment]
Thanks for the heads up!

I'm keeping this open so that others can find it easier, but you're welcome to close it.

**Comment by jekkel** [comment]
Picking up where it has been left - the build on circleCI seems to be broken since 2020/12/12 after @monotek merged https://github.com/kiwigrid/k8s-sidecar/commit/f116d0c525c714b89e1845eb01d4e2c2ae1ee36d

Probably the change from `pip` to `pip3` broke things. We're investigating.

**Comment by monotek** [comment]
Hmm... i guess ci should be changed to catch such errors.

**Comment by khernyo** [comment]
@jekkel, I see you started working on this issue. Thanks for that!

I will need a published k8s-sidecar image for version 1.5.0 in a couple of days. Do you think you can solve the issue soon, or should I just fork and publish it for myself?

**Comment by jekkel** [comment]
@manu11th was able to identify the build issue and promptly discovered a failing test thereafter. Both is going to be fixed with his PR https://github.com/kiwigrid/k8s-sidecar/pull/104

I think it's today or tomorrow we get this merged.

**Comment by khernyo** [comment]
Awesome, thank you!
