### ISSUE TITLE
docker tagging inconsistent

### ISSUE THREAD

**Issue by monotek** [kiwigrid/k8s-sidecar#105]
The docker tags are kind of messed up: https://hub.docker.com/r/kiwigrid/k8s-sidecar/tags?page=1&ordering=last_updated

The last tags in cronological order were:

* 1.9.0
* 0.1.388
* 1.3.0
* 0.1.275

**Comment by jekkel** [comment]
Indeed. It seems every commit on master is build twice. Once as a commit and - because another job tags the commit automatically with a semantic version - another time as a tag. The former crates the `0.x.x` versions the latter the "correct" versions.

Any idea where to fix that?

**Comment by monotek** [comment]
The correct tag seems to be set by a guithub action: 
https://github.com/kiwigrid/k8s-sidecar/blob/master/.github/workflows/main.yaml

The other one seems to come from circle ci:
https://github.com/kiwigrid/k8s-sidecar/blob/master/.circleci/config.yml#L58
