### ISSUE TITLE
Migrate from CircleCI to Github actions

### ISSUE THREAD

**Issue by jekkel** [kiwigrid/k8s-sidecar#109]
Github actions better integrated and work pretty well. We should migrate. 

Also see 
* https://github.com/kiwigrid/k8s-sidecar/issues/99#issuecomment-777595523
* https://github.com/kiwigrid/k8s-sidecar/pull/112#issuecomment-784939043
* https://github.com/kiwigrid/k8s-sidecar/pull/115#issuecomment-792372989

**Comment by monotek** [comment]
You might even be able to use the chart testing action (https://github.com/marketplace/actions/helm-chart-testing) and install the grafana helm chart (https://github.com/grafana/helm-charts/tree/main/charts/grafana) to test the k8s- sidecar as grafana makes use of it in the chart.

But might be a bit overklill and adds a rather big dependency.

You could copy a lot from: https://github.com/kokuwaio/helm-charts/blob/main/.github/workflows/ci.yaml
