### ISSUE TITLE
Feature request: multiple folders

### ISSUE THREAD

**Issue by holmesb** [kiwigrid/k8s-sidecar#11]
Currently only copies to a single directory.  Would be useful if this read a directory\folder label from each configmap to determine which directory on the destination pod's filesystem to create the file.  Workaround of a sidecar per folder is a bit hacky.

Use-case: Grafana supports its own folder system for storing dashboards in its UI.  It is dictated by the directory on the file-system the file is placed.  Using this sidecar currently, all dashboards must be placed in the same folder.

**Comment by Tim-Smyth** [comment]
Folder configurable via annotations now -> #15
