### ISSUE TITLE
parametrize period of watching changes

### ISSUE THREAD

**Issue by abdennour** [kiwigrid/k8s-sidecar#116]
https://github.com/kiwigrid/k8s-sidecar/blob/fe53300802c9112d4dc45d8fb296261f791339d8/sidecar/resources.py#L253

So instead of `sleep(5)`, we want to prametrize it and to be for example `sleep(os.getenv("PERIOD"))`

Could we avoid this hardcoded value ?

**Comment by jekkel** [comment]
Sure, should be easy to do
