### ISSUE TITLE
Received unknown exception: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte

### ISSUE THREAD

**Issue by DawidSwinoga** [kiwigrid/k8s-sidecar#118]
The problem appear when I store the truly binary data in Secret (for ex. certs. xlsx). I know that I can use ConfigMap and binaryData filed but I want to get original binary in my container not the base64 encoded (is it normal for binaryData field?).

I made one change in the way of base64 decoding and now configmap -> binaryData works as I expected. But I don't know if it's a good idea to change this behaviour?

```
def _get_file_data_and_name(full_filename, content, resource, content_type="ascii"):
    if resource == "secret":
        file_data = base64.b64decode(content).decode()
    elif content_type == "binary":
        # file_data = base64.decodebytes(content.encode('ascii'))
        file_data = base64.b64decode(content) # <----- now the file in destination directory contain original binary data instead of base64 encoded  
    else:
        file_data = content
```

**Comment by jekkel** [comment]
@DawidSwinoga Thanks for the report, I prepared a branch already in which I took the opportunity to simplify the code and extend tests. I think your intention is right though.

Stay tuned.
