### ISSUE TITLE
sidecar crashes with "message":"resourceVersion: Invalid value: \\"None\\"

### ISSUE THREAD

**Issue by naseemkullah** [kiwigrid/k8s-sidecar#13]
Hi, is there a workaround for the problem mentioned here (apart from reverting to v0.0.3 of sidecar):
https://github.com/helm/charts/issues/9136#issuecomment-445759760

sidecar continually crashes with
```
File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 10 Dec 2018 10:22:35 GMT', 'Content-Length': '186'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"resourceVersion: Invalid value: \\"None\\": strconv.ParseUint: parsing \\"None\\": invalid syntax","code":500}\n'
```

**Comment by gochist** [comment]
I updated the version of kubernetes to 8.0.1 and rebuild the docker image. It seems like to be fixed. 

https://github.com/kiwigrid/k8s-sidecar/blob/8e6c5fecd7e02044ded9fb8b0d070522e714da09/Dockerfile#L2

**Comment by naseemkullah** [comment]
Thanks @gochist

**Comment by gochist** [comment]
@naseemkullah I'm sorry for making confusion by deleting the comment. FYI, I fixed my problem temporarily by using an docker image which applied a workaround from https://github.com/kiwigrid/k8s-sidecar/pull/6#issuecomment-437158647

**Comment by naseemkullah** [comment]
ah ok I was confused as to why I did not see the comment haha

**Comment by naseemkullah** [comment]
closing issue, have not experienced it with latest version of sidecar
