### ISSUE TITLE
Need a matching Github release for kiwigrid/k8s-sidecar: v0.1.20

### ISSUE THREAD

**Issue by jabprab** [kiwigrid/k8s-sidecar#131]
https://hub.docker.com/layers/kiwigrid/k8s-sidecar/0.1.20/images/sha256-af151f677a63cdfcdfc18a4e3043520ec506d5e116692e5190f6f765dca42a52?context=explore

**Comment by jekkel** [comment]
Please explain this bug. Why would you need a matching github release for this 0.x.x version? It's pretty outdated and contains some security issues.

**Comment by jabprab** [comment]
I already have this docker image running in our environment. Need the same for our other environment to keep things in sync.
hence i need the same version.
we will be upgrading to the later versions once both the environment in sync

**Comment by jekkel** [comment]
But why would you need a github release for that? The image is available on docker hub tagged with `0.1.20` so you can just refer to it...?
```
docker pull docker.io/kiwigrid/k8s-sidecar:0.1.20
```

**Comment by jabprab** [comment]
I would require a Dockerfile with our customized contents in it. Basically i need to customize it and need to upload the image to my private repository.
How can i achieve this

**Comment by jekkel** [comment]
```
FROM docker.io/kiwigrid/k8s-sidecar:0.1.20
COPY ...
...
```
