### ISSUE TITLE
we  have a critical vulnerability in grafana helm chart

### ISSUE THREAD

**Issue by mithun-batabyal1-tm** [kiwigrid/k8s-sidecar#138]
Hi Team,

We have identified a critical vulnerability on k8s sidecar container, we have been using  old version(0.12)   in grafana  and so we decided  to upgrade the image repo with latest version (1.12.2)     and tried to deploy it, but still vulnerability is showing up.

code is being used:
sidecar:
  image: kiwigrid/k8s-sidecar:latest
  imagePullPolicy: IfNotPresent

Please help us on this.

Regards,
Mithun Batabyal
![sidecar_vul](https://user-images.githubusercontent.com/57533453/130785069-f37522f9-a3f6-4544-9f80-7bc528a95fcb.png)

**Comment by jekkel** [comment]
Could you provide more details? (For instance like done in #137?)

**Comment by arul-jegadish** [comment]
The latest version as of now (`1.15.0`) has three vulnerabilities classified as `High` in `Quay.io`:


<img width="1420" alt="Screen Shot 2022-01-23 at 12 23 38 AM" src="https://user-images.githubusercontent.com/5325547/150670507-84d70926-2821-4573-b88c-cfb97196c901.png">

**Comment by arul-jegadish** [comment]
👍
