### ISSUE TITLE
Security Vulnerability Items

### ISSUE THREAD

**Issue by dirkckau** [kiwigrid/k8s-sidecar#148]
Hi, 

We found some venerability items that might need some version upgrades. 

- Upgrade package busybox to version 1.33.1-r6 or above.
- Upgrade package ssl_client to version 1.33.1-r6 or above.
- Upgrade package libuuid to version 2.37.2-r0 or above.

![image](https://user-images.githubusercontent.com/91056335/146523650-e7adf081-82ca-4e69-9ff4-d25c20887856.png)

Is there any release plan?

**Comment by jekkel** [comment]
Any idea whether those are fixed in the base imge (`python:3.8-alpine`) ? If we can release a rebuild on top of an updated base image.

**Comment by jekkel** [comment]
Can you please scan just released v1.14.3?

If the vulnerabilities are still in there I guess we'd need to report this upstream.

**Comment by dirkckau** [comment]
Hi, this image is "no issue" (1.14.3)

**Comment by jekkel** [comment]
Fixed with `1.14.3`

Thanks for the report though!
