### ISSUE TITLE
Security Vulnerability: expat

### ISSUE THREAD

**Issue by bartkeizer** [kiwigrid/k8s-sidecar#164]
Hi,

A critical dependency in k8s-sidecar was found by our scanning tool Twistlock:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/4185081/154706196-4f41a26b-6e34-42c2-bc67-98c42485de89.png">

Is it possible to update the package 'expat'?
Thanks in advance!

**Comment by jekkel** [comment]
Is our base image `python:3.10.2-alpine` also affected?

**Comment by bartkeizer** [comment]
This is indeed an issue in the base image: https://github.com/docker-library/python/issues/696.
The proposed solution is a `apk upgrade --no-cache` in the k8s-sidecar image (https://github.com/docker-library/python/issues/696#issuecomment-1043322751).
