### ISSUE TITLE
empty folder should be removed

### ISSUE THREAD

**Issue by XuanhuiHu** [kiwigrid/k8s-sidecar#168]
When dashboard created with k8s-sidecar-target-directory annotation, there is a folder has been created.
But the folder will exist persistently even if the folder is empty when the dashboards are all removed.

**Comment by jekkel** [comment]
Why is this an issue?

**Comment by XuanhuiHu** [comment]
> Why is this an issue? Can you give it a script to execute after each change (using `SCRIPT` configuration) which recursively deletes empty folders?

The reason is there will be an empty folder in Grafana, not only in the filesystem.

I will try this feature, and report later.
Thanks for your help.

**Comment by XuanhuiHu** [comment]
Hi, I removed the directory in filesystem, there is still a folder in Grafana, so I think the problem is not here.
