### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED when connects to kubernetes apiserver

### ISSUE THREAD

**Issue by wu105** [kiwigrid/k8s-sidecar#18]
Sidecar should provide an option to supply kubernetes apiserver ca certificate, as a configure map, secret, or via other means, and/or an option to turn off the verification of the apiserver ssl certificate.

This is the same as https://github.com/helm/charts/issues/11287

The kubernetes apiserver CA certificate usually is not in the trusted certificate bundle thus the sidecar (image tag 0.0.6) would usually fail with the error documented in the referenced issue.
The option to supply the apiserver CA certificate or turn off the https  server ssl verification need to be added to sidecar before the downstream helm charts can offer related options.

**Comment by Tim-Smyth** [comment]
The least desirable option of turning of the verification was implemented. Hope your problem is solved with this. Please reopen if not. Thanks

**Comment by wu105** [comment]
It does provide a work around.  Can we make SKIP_TLS_VERIFY=true the default?  Currently the down stream helm charts (grafana and Prometheus-operator) picked up the new image but not the option, thus we have to modify those charts somehow.  You can make  SKIP_TLS_VERIFY=false the default dynamically when you add the custom certificate option AND the custom certificate is provided.

**Comment by den-is** [comment]
Totally agree with @wu105 
It make life so much easier
```
SKIP_TLS_VERIFY=true
```
