### ISSUE TITLE
Encode username and password with utf-8 to support special chars

### ISSUE THREAD

**Issue by r0bnet** [kiwigrid/k8s-sidecar#183]
Hey,

I found this issue with requests: https://github.com/psf/requests/issues/6094

Now I'm not able to use some special chars in the REQ_PASSWORD field (found in grafana helm chart). The solution seems to be encoding username and password with `utf-8` because otherwise it will be encoded with `latin1` which is not working (base64 result is not correct anymore).

For testing you can try using a password that contains `§`.

Is that an option?

r0bnet

**Comment by jekkel** [comment]
Could you try the version from #184 ?

**Comment by jekkel** [comment]
There are some automated tests which success on the branch but we've got no coverage for basic auth use cases yet. Would you mind adding one?

**Comment by jekkel** [comment]
@r0bnet maybe you can test it on your site with the PR-built images available here: https://github.com/kiwigrid/k8s-sidecar/actions/runs/2293149348 ?

**Comment by r0bnet** [comment]
Hey @jekkel will try to do so but I'm not able to test it before next week. Thanks for sharing the image

**Comment by jekkel** [comment]
@r0bnet please try with just released `v1.20.0`
