### ISSUE TITLE
Feature request - Ability to set log level

### ISSUE THREAD

**Issue by nhuray** [kiwigrid/k8s-sidecar#189]
Hi,

Thanks for that project, it's really useful ! 

That project is used in the Grafana [Helm chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L649) to load dashboards defined as ConfigMap into the Grafana container.

I noticed once I deployed some dashboards that the sidecar is generating a lot of logs which has an impact on cloud cost:
<img width="1709" alt="Screen Shot 2022-05-24 at 9 03 57 AM" src="https://user-images.githubusercontent.com/958983/170041577-3d562ce0-6bad-4ac4-8d60-d93d711b55d6.png">
<img width="1699" alt="Screen Shot 2022-05-24 at 9 03 36 AM" src="https://user-images.githubusercontent.com/958983/170041581-4e7fff5c-8994-4b09-b0c5-a686d34a8a46.png">

I did not find a way to control the log level passing an environment variable and looking at the code it looks like the project is not using any logging library (just using `print`). 

So would you be interested to have the ability to control the log level (I can submit a PR if needed) ?

Regards,

**Comment by jekkel** [comment]
Hi @nhuray 

a contribution introducing a (light weight) logging framework and some configuration options to configure logging would be greatly appreciated.

**Comment by schans** [comment]
+1 on this one. Was about to create the same ticket. Imho the default python logging framework would suffice. Might need a little bit of tuning on what level what should be logged. 

As to how to set the log level: maybe keep that in line with the other configuration and introduce a LOG_LEVEL environment variable?

**Comment by schans** [comment]
Maybe something like:

`
import logging

def set_logging(l):
    loglevel = os.getenv(LOG_LEVEL, "INFO")
    numeric_level = getattr(logging, loglevel.upper(), None)
    if not isinstance(numeric_level, int):
        raise ValueError('Invalid log level: %s' % loglevel)
    logging.basicConfig(level=numeric_level, format='%(asctime)s %(levelname)s %(message)s')
`

**Comment by jekkel** [comment]
released with [v1.19.0](https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.19.0)

**Comment by ftpd** [comment]
@nhuray @jekkel any idea, how to set it when deploying Grafana from their helm chart? It [doesn't look like](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L192-L232) I can just simply specify this env variable in my deployment.

**Comment by schans** [comment]
Did you try to set it with `env` ? https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L381 Haven't tested it myself though.

**Comment by ftpd** [comment]
I haven't tried with the 'global' one, but the code I've linked in the previous post suggests it is not that easy.

I've opened the issue in grafana/helm-charts and I'm going to submit a PR. But thanks for replying anyway!
