### ISSUE TITLE
Search only in current or specific namespace

### ISSUE THREAD

**Issue by eloo** [kiwigrid/k8s-sidecar#2]
Hi,
would it maybe be possible to make the sidecar configurable to search only in a specific or the actual namespace?
In our setup we use namespaces to separate teams and so we don't have access to search in all namespaces.. which is btw not neccessary in our usecase.. so simply set the namespace where the sidecar is looking for config maps would already fit our needs.

Whats you opinion on such a change?
Thanks

**Comment by Tim-Smyth** [comment]
Hi @eloo,
I think your request would definitely be a good addition to the functionality. The API offers the function [link](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#list_namespaced_config_map) for that too.

Just an idea/question: Do you think the use case could appear (in your company) that more than one namespace should be watched?
Would restricting the permissions via Role/RoleBinding to a specified namespace work too?

Thanks

**Comment by eloo** [comment]
@Tim-Smyth Hmm not sure.. maybe for some more general dashboards but i guess the default use case would be to only look in your own namespace..
Normally namespaces shouldn't known something about each other in our case

**Comment by eloo** [comment]
@Tim-Smyth im not sure if my python skills and knowledge of the api is enough :D 
further i don't know when i'm having time for that

**Comment by eloo** [comment]
okay.. after short testing it seems to work like with exchanging the for event in w stream line with this
```
for event in w.stream(v1.list_namespaced_config_map, namespace="space_name"):
```
but i don't know how to pass or retrieve the current namespace

**Comment by giacomoguiulfo** [comment]
@eloo for the current namespace look at https://github.com/kiwigrid/k8s-sidecar/pull/7
