### ISSUE TITLE
Confused by the 'Why', k8s mounted ConfigMaps upload live

### ISSUE THREAD

**Issue by whereisaaron** [kiwigrid/k8s-sidecar#21]
Hi, this sidecar looks like a useful tool regardless, but I was confused by the 'Why' in the README:

> "Why?
> Currently (April 2018) there is no simple way to hand files in configmaps to a service and keep them updated during runtime."

Files in ConfigMap (and Secrets) are updated live at runtime wherever they are mounted. That is their intrinsic property I think forever, but certainly in k8s 1.4+ in 2016. The only time they don't update live at runtime is if you mount them using the new `subPath` option or if you map them into environment variable.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
> **Mounted ConfigMaps are updated automatically**
> When a ConfigMap already being consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted ConfigMap is fresh on every periodic sync. However, it is using its local ttl-based cache for getting the current value of the ConfigMap. As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period + ttl of ConfigMaps cache in kubelet.
> 
> Note: A container using a ConfigMap as a subPath volume will not receive ConfigMap updates.

I use this property all the time to live update configuration in running services. I use sidecars also, but using just to watch for the live updates and ping the service to re-read them.

This sidecar is probably more flexible that that built-in live update support, and handles the 'ping' bit too.

**Comment by Tim-Smyth** [comment]
Hi @whereisaaron,
You are right the cm's you have configured in your deployment/pod/whatever are automatically updated. But sometimes you don't want to configure them in your deployment. This sidecar container was my solution for following problem: I have grafana in my cluster and deploy several other services too. I don't want to touch the grafana deployment everytime i install/uninstall a service. But I also want the dashboards that the services have to be imported into grafana (and deleted too).
I hope you can follow my motivation. If more questions occur pls ask :)

**Comment by whereisaaron** [comment]
Yep, as I said this sidecar definitely has additional benefits. The 'why' in the README just made it sound to me like live ConfigMap updates are possible/normal.

That use case is a good example. With this sidecar, you can create entirely new resources and have them injected into a running Pod without have to patch, and thus restart the Pod. 👏
