### ISSUE TITLE
Findings on kiwigrid/k8s-sidecar:1.19.5

### ISSUE THREAD

**Issue by vartikavr** [kiwigrid/k8s-sidecar#228]
Hi team,
We are currently using kiwigrid/k8s-sidecar:1.19.5 images, which are being marked as vulnerable with below descriptions:

| Vulnerability Name | Image Id | Description | Solution |
| --- | --- | --- | --- |
| Alpine Linux Security Update for expat | sha256:84866dc00a241ec35dbd2b74264f7b161d75d46831796851723380eda4a6f2f5 | Alpine Linux has released a security update for expat to fix the vulnerabilities. Affected versions: Alpine Linux 3.14 Alpine Linux 3.15 Alpine Linux 3.16 Affected Package versions prior to 2.4.9-r0. | Refer to Alpine Linux advisory for updates and patch information. Patch: Following are links for downloading patches to fix the vulnerabilities: [expat-2.4.9-r0:Alpine Linux](https://security.alpinelinux.org/srcpkg/expat) |
| Alpine Linux Security Update for expat | sha256:cc906e4efaa0fa27cb3cb61d34bf225c401061f3acbea36feb26c48936e664c1 | Alpine Linux has released a security update for expat to fix the vulnerabilities. | Refer to Alpine Linux advisory [expat](https://security.alpinelinux.org/srcpkg/expat) for updates and patch information. |
| Alpine Linux Security Update for expat | sha256:dfa0717b9a21b5a3cb2e1d97da1cd15bf3100312a639d9d39153de7e73b7a5d3 | Alpine Linux has released a security update for expat to fix the vulnerabilities. | Refer to Alpine Linux advisory [expat](https://security.alpinelinux.org/srcpkg/expat) for updates and patch information. |

Kind request to please assist us with its plan for fixes.

**Comment by hpvd** [comment]
there is a fresh new full release of alpine 3.17, see https://www.alpinelinux.org/posts/Alpine-3.17.0-released.html

**Comment by vartikavr** [comment]
Shifting to the newer version helped. Thanks. Closing this issue.
