### ISSUE TITLE
Consider Switching to Chainguard's Python Image?

### ISSUE THREAD

**Issue by dlorenc** [kiwigrid/k8s-sidecar#242]
Hey!

I noticed a few CVEs in the image published here, as well as a few issues and PRs to address them:
https://github.com/kiwigrid/k8s-sidecar/issues/238
https://github.com/kiwigrid/k8s-sidecar/issues/215
https://github.com/kiwigrid/k8s-sidecar/pull/232

I took a pass at converting this to the Chainguard Python image in a fork: https://github.com/kiwigrid/k8s-sidecar/compare/master...dlorenc:k8s-sidecar:cgr?expand=1

The image is also available at ghcr.io/dlorenc/k8s-sidecar for testing.

Would you be interested in trying this out? If so I could clean this up and send a few PRs.

**Comment by jekkel** [comment]
Hi @dlorenc 

looks interesting. Do you know the versioning and update strategy of those images? I would prefer immutable image tags but unfortunately our current base images rebuild often into the same "floating" tag. This way dependabot is not really able to detect updates (adding the sha to the tag breaks multi-arch builds via buildx I believe). If they reliably publish new versions for updated dependencies then this might be worth the switch already.

**Comment by dlorenc** [comment]
We can do either floating tags or immutable ones - what would your ideal tagging strategy look like here? I'm happy to help get that supported.

**Comment by jekkel** [comment]
As said: immutable tags for which dependabot can correctly infer updates (and CVEs) would be best.

**Comment by dlorenc** [comment]
So something date-time based? Or tied to the versions of the packages underneath somehow?

**Comment by jekkel** [comment]
I'd vote for semantic versioning, but those base images tend to be a baseline of multiple versions really, some of which are important for compatibility, some not. And I'm afraid there's no common way of aggregating semantic versions, is there?

**Comment by dlorenc** [comment]
Yeah that's kind of the general issue with tagging images. Every bump is somewhat semantic depending on how you look at it.
