### ISSUE TITLE
when listing secrets and configmaps, secrets fail with 'V1Secret' object has no attribute 'binary_data'

### ISSUE THREAD

**Issue by ThommyH** [kiwigrid/k8s-sidecar#265]
We have a mix of configmaps and secrets for grafana datasources. When the sidecar tries to load the secrets it fails. Neither the configmaps nor the secrets use binary data:

`Traceback (most recent call last):
  File "/app/sidecar.py", line 155, in <module>
    main()
  File "/app/sidecar.py", line 113, in main
    list_resources(label, label_value, target_folder, request_url, request_method, request_payload,
  File "/app/resources.py", line 128, in list_resources
    files_changed |= _process_config_map(dest_folder, item, resource, unique_filenames, enable_5xx, True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/resources.py", line 217, in _process_config_map
    if config_map.binary_data is not None:
       ^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'V1Secret' object has no attribute 'binary_data'`
       
We tried running with the latest version 1.23.1 but that didnt help.

**Comment by ThommyH** [comment]
I suspect the cleanup method here to be the culprit: https://github.com/kiwigrid/k8s-sidecar/blob/062edb9dde19e5a4c6cf96c0a05cf1633a9a7edf/src/resources.py#L124

It ignores the kind of resources saved in there. Therefore when reaching this line when loading configmaps, it sees the previously added secret and then assumes it is a configmap.

**Comment by jekkel** [comment]
Thanks for the report, indeed the cleanup code looks broken a bit...

@tomrk-esteam8 could you try fixing that? I think it's a matter of detecting the resource type from `item` instead. Even extending the test should be easily possible.

**Comment by tomrk-esteam8** [comment]
@jekkel ok, I will take. a look.

**Comment by mario-steinhoff-gcx** [comment]
Hey, I fixed this in my local branch, PR will follow shortly.
