### ISSUE TITLE
vulnerabilities in libcrypto and libssl libraries

### ISSUE THREAD

**Issue by marianobilli** [kiwigrid/k8s-sidecar#266]
Upon running a trivy vulnerability scan with
```
docker run --rm -v trivy-cache:/root/.cache/ -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image kiwigrid/k8s-sidecar
```
Both libraries should be bumped to, at least, version `1.1.1t-r2`
<img width="1133" alt="Screenshot 2023-03-31 at 10 32 57" src="https://user-images.githubusercontent.com/14143004/229069413-440911e4-5e1b-4ff6-9f45-18371d676419.png">

Thanks

**Comment by jekkel** [comment]
Thanks for the report, can you please check whether our upstream base image is affected as well?

**Comment by bt909** [comment]
This issue is solved with the actual image, I think, but there are new findings.
see: https://github.com/kiwigrid/k8s-sidecar/issues/299

But I think this issue can be closed.

**Comment by ChristianGeie** [comment]
yeah, let me close this issue and we'll continue it in [#299](https://github.com/kiwigrid/k8s-sidecar/issues/299)

**Comment by ChristianGeie** [comment]
yeah, let me close this issue and we'll continue it in [#299](https://github.com/kiwigrid/k8s-sidecar/issues/299)
