### ISSUE TITLE
Additional binaries for the Sidecar Script 

### ISSUE THREAD

**Issue by hinrichd** [kiwigrid/k8s-sidecar#271]
Hi, 

is it possible to add additional binaries to the sidecar container like curl or jq?

[Node-Red Helm Chart ](https://github.com/SchwarzIT/node-red-chart)is using this sidecar container to store config maps in the container and running a shell script afterwards which will reload the stored config maps in the main container. Unfortunately the script fails in the sidecar container as it is using curl (API Request) and jq (json parser) as it is not present in the container image. 

I also have opened a ticket in the [node-red issues](https://github.com/SchwarzIT/node-red-chart/issues/236). 

What do you thing is the best way to solve this?! Is it possible to add curl an jq to the requirements.txt?

**Comment by hinrichd** [comment]
Hi @jekkel, 
thank you for your reply. Totally understand your answer and thank you for pointing us into the right direction. 
This little API Request will indeed possible with python requests. However I have never been scripted with python before. 
Many Thanks

**Comment by hinrichd** [comment]
Hi @jekkel 
I have rewritten the shell script with curl/jq to pyhton using request and json. The script actually works in the k8s-sidecar container by running manually inside the container. So, no need for extra binary or packages, so far. 

Obviously the `SCRIPT` configuration environment variabel will only run sh scripts after configmaps or secrets have changed. So, how can I run my python script ?

**Comment by jekkel** [comment]
If you mount both the python file AND a small shell script only invoking the python file...?
I can imagine that we could change the execution of scripts to work with shebangs so that the python file itself could be referred to by `SCRIPT`...

**Comment by jekkel** [comment]
> sh /app/my-py-script.py will not work even with the python shebang #!/usr/bin/env python

I know and that's what I meant with that we can probably change the invocation strategy to support shebangs. This would be an enhancement, it is not yet supported.

Glad that you made it work in a shell script through stdin though!

Would you mind closing this issue in favor of a new one requesting support for python scripts having a valid shebang line?

**Comment by onedr0p** [comment]
It would be nice if this would be revisited it, using jq and curl would mean we do not need to write python to have a simple script to something when the `SCRIPT` env is use. I get the need to have minimal attack surface but having python included is already stretching it pretty wide.

**Comment by ChristianGeie** [comment]
@onedr0p I would like to understand what exactly is the reason for putting more binary into the image. The use case of the sidecar is clearly described and it should fulfill this. If there are understandable reasons to extend this use case, then this should be done in Python.

**Comment by onedr0p** [comment]
> I would like to understand what exactly is the reason for putting more binaries into the image.

I get Python is there and pretty much all use-cases could be solved with writing a Python script, however a script in bash with curl/jq is so much easier to write and maintain than writing a Python script to just call a HTTP endpoint when a configmap or secret is changed.. I really don't get why having more options available to cluster operators by including these two tools is so controversial. 🤷🏼‍♂️
