### ISSUE TITLE
Append name of namespace and configmap to the filename

### ISSUE THREAD

**Issue by joaogbcravo** [kiwigrid/k8s-sidecar#28]
AFAIK, at this moment, k8s-sidecar will load to the same file, configs with the same name (cm.data.key), regardless being provided for a different configmap or from a different namespace.

Would be possible to append both the namespace and the configmap name to avoid this behaviour?

The alternative, seems uglier: would force us to append the namespace and configmap name to the  cm.data.keys.

**Comment by Tim-Smyth** [comment]
Well you can make a PR to optionally add this feature, but for us the splitting into folders base on the configmap label is sufficient.

**Comment by Tim-Smyth** [comment]
Closed for now. If you are still interested reopen pls
