### ISSUE TITLE
Offer for help / Feature request: Read/Watch secrets

### ISSUE THREAD

**Issue by fr-ser** [kiwigrid/k8s-sidecar#31]
Hello,

I wanted to implemented some functionality in an upstream project (grafana helm chart) and was looking for the ability to watch secrets as well as configmaps.

Currently this project does not seem to support that, but I would appreciate this functionality very much. I can also offer to implement it, in case this project is still active and this functionality fits into the scheme of things.

So... Want me to take a crack at enabling secret watching? I think this should not be a breaking change.

**Comment by Tim-Smyth** [comment]
Hi Sergej,
Thank you for your offer. Our team doesn't need that functionality at the moment but that should not stop you. If you are willing to implement it, we would be happy to review and merge it.

**Comment by fr-ser** [comment]
Would it be alright if I add some unit tests with pytest to this project?

**Comment by Tim-Smyth** [comment]
Unit tests would be awesome. Once I am back from vacation I want to set up CI pipeline too.

**Comment by fr-ser** [comment]
Alright. Once the initial branch is merged I would take a stab at adding those then :+1:

**Comment by Tim-Smyth** [comment]
Sorry that PR took so long, don't really have an excuse. I will do my best to get the next one fast done. Thank you very much for your contribution :+1:
