### ISSUE TITLE
Strict kubernetes client version dependency

### ISSUE THREAD

**Issue by janotav** [kiwigrid/k8s-sidecar#35]
Hi,

Currently the dependency requirement for the kubernetes python library is declared using strict version: kubernetes==8.0.1

Would it be possible to have this relaxed to allow newer versions of the library? I believe that the compatibility matrix of the kubernetes client generally allows using newer client with older server, so there should be no harm in relaxing the upper bound, right?

**Comment by Tim-Smyth** [comment]
The idea was to make the build as repeatable as possible. I would rather update the lib regularly than have a surprise when we build. Would you be ok with an updated lib for now?

**Comment by janotav** [comment]
Yes, that should be fine I guess. My use-case is a bit strange and driven by legal process (third party library approval) rather than technical requirements. Do whatever you think is best for the project...

**Comment by Tim-Smyth** [comment]
Updated deps
