### ISSUE TITLE
Multi-arch image

### ISSUE THREAD

**Issue by mcanevet** [kiwigrid/k8s-sidecar#48]
Would it be possible to provide multi-arch (especially amd64 and arm64 in my case) images on DockerHub. This images is used in prometheus-operator and I try to deploy it on a mixed arch cluster.

**Comment by gclawes** [comment]
Looks like CircleCI doesn't yet support ARM builds: https://ideas.circleci.com/ideas/CCI-I-900

**Comment by fahlke** [comment]
***My personal workaround (until CircleCI supports Multi-Arch)***

Create your image with `docker buildx` and push it to your container registry.
Change to your desired platform listed in `docker buildx ls`.

> **Note:** I'm running this in a K3s cluster on Raspberry Pi 3.

### Build custom image

```bash
git clone https://github.com/kiwigrid/k8s-sidecar.git \
  --depth 1 \
  -b 0.1.110 \
  /tmp/k8s-sidecar

pushd /tmp/k8s-sidecar

  docker buildx build \
    --platform "linux/arm/v7" \
    -t quay.io/<USERNAME>/grafana-k8s-sidecar:0.1.110 .

  docker tag \
    quay.io/<USERNAME>/grafana-k8s-sidecar:0.1.110 \
    quay.io/<USERNAME>/grafana-k8s-sidecar:latest

  docker image inspect \
    quay.io/<USERNAME>/grafana-k8s-sidecar:0.1.110 | jq '.[].Architecture'

  docker login \
    --username "<USERNAME>" \
    quay.io

  docker push quay.io/<USERNAME>/grafana-k8s-sidecar:0.1.110
  docker push quay.io/<USERNAME>/grafana-k8s-sidecar:latest

popd
```


### Installation 

Install the chart with your custom image via `--set` or `values.yaml`.

```bash
helm install grafana stable/grafana \
  --namespace monitoring \
  ...
  --set "sidecar.datasources.enabled=true" \
  --set "sidecar.image=quay.io/<USERNAME>/grafana-k8s-sidecar:0.1.110"
```

### Verification

```bash
$ kubectl -n monitoring logs grafana-557c6856d-8zqzq -c grafana-sc-datasources
Starting collector
No folder annotation was provided, defaulting to k8s-sidecar-target-directory
Selected resource type: ('secret', 'configmap')
Config for cluster api loaded...
Working on secret: monitoring/grafana-datasource

$ kubectl -n monitoring exec -it grafana-557c6856d-8zqzq -- /bin/ash -c 'ls -lAs /etc/grafana/provisioning/datasources'
total 4
     4 -rw-r--r--    1 grafana  grafana        224 Apr  5 11:29 datasource.yaml
```

**Comment by ramsrib** [comment]
I forked and added multi-arch support using `travisci`: https://github.com/ramsrib/k8s-sidecar.

For a quick workaround, use this public image:
```
sidecar.image: ramsrib/k8s-sidecar
```

**Comment by mrueg** [comment]
Looking at the recent comments in https://ideas.circleci.com/ideas/CCI-I-900
It seems there is a solution for circleci now as well: https://github.com/elementary-robotics/atom/blob/master/.circleci/config.yml
