### ISSUE TITLE
Missing releases on Github

### ISSUE THREAD

**Issue by arminc** [kiwigrid/k8s-sidecar#58]
I can see two releases on Docker hub (0.1.20 being the latest one) which don't have a GitHub release. Can the releases still be created or can a new release be made which has both?

**Comment by axdotl** [comment]
Created a GitHub release matching the related docker tag `0.1.63`

**Comment by jabprab** [comment]
Any matching github release for the below  docker image?.
https://hub.docker.com/layers/kiwigrid/k8s-sidecar/0.1.20/images/sha256-af151f677a63cdfcdfc18a4e3043520ec506d5e116692e5190f6f765dca42a52?context=explore

**Comment by jekkel** [comment]
> Any matching github release for the below docker image?.
> https://hub.docker.com/layers/kiwigrid/k8s-sidecar/0.1.20/images/sha256-af151f677a63cdfcdfc18a4e3043520ec506d5e116692e5190f6f765dca42a52?context=explore

No.

Before we fixed the tag names and versioning the build added build numbers as image tags leading to inconsistencies and confusion.

Please consider all version below 1.0.0 unmaintained and unsupported and please upgrade. Sorry for any inconvenience this causes.
