### ISSUE TITLE
Renaming key in config map causes duplicate files to exist

### ISSUE THREAD

**Issue by davidnortonjr-sps** [kiwigrid/k8s-sidecar#59]
If I have a ConfigMap with:

```
data:
  foo.json: whatever
```
And change the key inside it to:

```
data:
  bar.json: whatever
```

Then both `foo.json` and `bar.json` will exist in my target directory. I would expect `foo.json` have been removed.

**Comment by axdotl** [comment]
Hello, 
you're right, target directory should be tidy.
You are very welcome to create a PR for this.
