### ISSUE TITLE
Working with other side-cars

### ISSUE THREAD

**Issue by haf** [kiwigrid/k8s-sidecar#75]
It would be great to provide workaround-hooks in this container.

Problem:

- Given that Grafana only reads [datasources on start](https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources)
- Given that GKE doesn't support anything but ReadWriteOnce persistency (else I'd spawn a Job with a shared PVC)
- Given that I use Istio in the Grafana namespace
- Given that Istio's istio-proxy sidecar container is needed to access to the k8s API
- Given that I was using k8s-sidecar to list datasources from the k8s API as an init container
- And given that [k8s KEP #753](https://github.com/kubernetes/enhancements/issues/753) is not yet done
- I have a crashing init sidecar
- Or else if I move it to "containers" and make it "WATCH" instead of "LIST", I could have it run continously,
- However, see point 1, so we have a race condition

A workaround:

- Suppose this container exposed a HTTP interface that only returned 200 OK once "one watch iteration" was done
- I could then do

```
command: ["/bin/bash", "-c"]
args: ["until curl --head localhost:15000 ; do echo Waiting for Sidecar; sleep 3 ; done ; echo Sidecar available; ./init-stuff.sh && ./startup.sh"]
```

**Comment by dudicoco** [comment]
@haf why not just sleep for n seconds instead?

**Comment by haf** [comment]
Instead of polling? Because there's no guarantee it'll be ready in N seconds. @dudicoco

**Comment by haf** [comment]
This is really crap automation.

**Comment by jekkel** [comment]
It seems you could use the `SCRIPT` configuration to touch a file as soon as the listing succeeds. Your bash waiting wouldn't then refer to an http request but the existence of that file.
