### ISSUE TITLE
Retries way too quickly

### ISSUE THREAD

**Issue by haf** [kiwigrid/k8s-sidecar#76]
When you launch this sidecar next to a grafana container, you get a couple of pages of logs that the connection to k8s api is failing due to istio-proxy not having been initialised yet.

It would be great if this repo would implement an exponential decorrelated backoff to avoid this problem; wait, say 20 seconds, before crashing, too. That way, the grafana pod doesn't have to get 2 restarts before stabilising.

**Comment by haf** [comment]
.

**Comment by jekkel** [comment]
That dot is not really helpful, is it?

The issue you described seems to relate somewhat to #75. Nonetheless, as the sidecar just uses official k8s client libraries they probably support something similar already? Or would we need to wrap all calls in a exponentially back-off wrapper?

Any pointers welcome!

And we ❤ PRs

**Comment by haf** [comment]
@jekkel Well, the bot is not really helpful, is it and noone's replied in a year.

It's not very related; retrying in code is not that related to sidecars actually, hence I filed two separate issues.

**Comment by jekkel** [comment]
Actually this is not fixed with #135 because this issue is about retrying the k8s api which is hidden within the python k8s client library.

**Comment by jekkel** [comment]
by using the retry configuration options this can be done.
