### ISSUE TITLE
More descriptive POST response

### ISSUE THREAD

**Issue by holmesb** [kiwigrid/k8s-sidecar#78]
Currently the log output after a POST is attempted can be misleading.   
[res.reason](https://github.com/kiwigrid/k8s-sidecar/blob/8479802e5351096c93ca5a59722c9ce08106075b/sidecar/helpers.py#L79) gives "[Response: 200 OK]" even when the text of the response (res.text) is an error.

**Comment by jekkel** [comment]
released with 1.0.0
