### ISSUE TITLE
Existing  tags on Docker Hub are missing on Github repo 

### ISSUE THREAD

**Issue by llsousa** [kiwigrid/k8s-sidecar#87]
Currently, the latest tag on GitHub is 0.1.144 and on Docker Hub is 0.1.178 (0.1.151 and 0.1.57 also exists between 0.1.144 and 0.1.178).

Can you please add the missing tags on GitHub?

Thanks.

Related to #58 .

**Comment by pulledtim** [comment]
Hi @llsousa, 
For the future all master builds will be tagged automatically. Does this help you or shall i tag the old versions too?

**Comment by llsousa** [comment]
@pulledtim , thank you for work, That's ok.
