### ISSUE TITLE
Support for comma separated namespaces

### ISSUE THREAD

**Issue by Miouge1** [kiwigrid/k8s-sidecar#9]
It would be nice if `NAMESPACE` would take a comma separated list of namespaces:
```
export NAMESPACE=foo,bar
```
Would scan namespace `foo` AND `bar` for ConfigMaps

**Comment by Tim-Smyth** [comment]
Sorry this issue must have slipped by. Sounds like a nice feature, I currently don't have time to add it but you are welcome to do so.

**Comment by jekkel** [comment]
Reopened because there's a fresh PR available.

**Comment by jekkel** [comment]
released with [v1.13.0](https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.13.0)
