### ISSUE TITLE
Couldn't start Jenkins because of Docker rate limit

### ISSUE THREAD

**Issue by erihanse** [kiwigrid/k8s-sidecar#99]
Hello,
as many of us know, Docker is enforcing rate limits on the amount of pulls we can do (https://docs.docker.com/docker-hub/download-rate-limit/#kubernetes). This led to us being unable to start Jenkins in kubernetes, due to jenkins having a dependency of this image. I just wondered if there were any plans to host this image on another repository than docker hub? Or is there any plans to apply for open source status, as mentioned in https://www.docker.com/blog/expanded-support-for-open-source-software-projects/?

**Comment by jekkel** [comment]
I hate to say this but we cannot really help. We do not plan to apply for the open source status. Hosting and serving images incurs costs and enforcing a rate limit is an understandable way of limiting expenses.

That being said I see the following options:
* hosting a private repository proxying or replicating from docker hub (e.g. [using Harbor](https://tanzu.vmware.com/developer/guides/kubernetes/harbor-as-docker-proxy/))
* authenticating with docker hub on pull and buying a subscription

see also https://www.whoownsmyavailability.com/ ;)

**Comment by monotek** [comment]
quay.io or github container registry could be used.
imho also a good possibility to switch to github actions entirely.

**Comment by jekkel** [comment]
PRs welcome.

Note that Github Container Registry is advertised as beta and might become a paid service as well.

**Comment by jekkel** [comment]
all current tags are synchronized to quay.io
new tags are going to be pushed directly (given #108 is merged)
